---
path_repository: ""
data_name_file: "_25" #"_split" #"_75"
data_language: "pauq_" #"" #"pauq_"
pre_train_tokenizer: "bert-base-cased" #"FacebookAI/roberta-base" #"bert-base-cased" #"cointegrated/rubert-tiny"
path_data_schema: "data/pauq_tables.json" #"data/pauq_tables.json" #"data/table_id2new_attrs_for_parsing.json"
path_query_vocab: "data/query_vocab_pauq.json"
batch_size: 16 #16
max_sent_len: 170 # 170, 240
separate_batch: -1