---
pre_train_model: "bert-base-cased" # "FacebookAI/roberta-base" #"bert-base-cased" #"cointegrated/rubert-tiny"
learning_rate: 0.0001
sched_step: 40 # 40
sched_gamma: 0.1
epoch_num: 40 # 40
try_one_batch: False # True, False